### PR TITLE
Feature/text lint

### PR DESCRIPTION
**Pull request by jason-fox**
Fixing https://github.com/Fiware/dataModels/issues/314 - also fixing deadlinks and whitespace issues.

### CODE REVIEW

**Comment by jason-fox** [comment]
@Joudsi - Would you like to comment on this PR?

**Comment by jmcanterafonseca** [comment]
we need to check that this PR is not breaking formatting, as previous linting PRs did ... 

@joudsi, could you verify? 

@jason-fox this text linting why is it needed?

**Comment by jason-fox** [comment]
@jmcanterafonseca  @Joudsi 

I think I'm done now. Could you review?

**Comment by Joudsi** [comment]
@jason-fox - Regarding the indentation and the sub-bullets, all looks good to me.

Thanks!

**Pull request merged**
