### PR TITLE
Add new category types to Device data models

### PR DESCRIPTION
**Pull request by fdelavega**
#425

### CODE REVIEW

**Comment by jmcanterafonseca** [comment]
you would need to also update the spec.md and to provide links to ADAPT specifications, including the meaning of each new type of device

**Comment by fdelavega** [comment]
Not so sure that there is an ADAPT specification I can reference more that the C# file you included in the issue. Al least I haven't found documentation in this regard

**Comment by jmcanterafonseca** [comment]
@fdelavega you need to check IoF2020 UC1.4 input and the links to ADAPT https://github.com/ADAPT/ADAPT/tree/develop/source/ADAPT

**Comment by fdelavega** [comment]
There is no class for describing the DeviceElementType elements more than the C# enum, in some cases I can point to the C# config class, (Like ImplementConfiguration.cs) but I don't think this is the proper link

**Comment by jmcanterafonseca** [comment]
@fdelavega can we find other devices from SAREF4Agri? and complete this work?

https://mariapoveda.github.io/saref-ext/OnToology/SAREF4AGRI/ontology/saref4agri.ttl/documentation/index-en.html

thanks!

**Pull request merged**
