### PR TITLE
Added areaServed property + examples

### PR DESCRIPTION
**Pull request by nagyszblcs2**

### CODE REVIEW

**Comment by jmcanterafonseca** [comment]
this PR is extremely poor for not saying a worse word. Please check other Data Models, syntaxes, etc. We are all in a hurry but that does not mean submitting anything ...

**Comment by nagyszblcs2** [comment]
Hi Jose,

I asked you to guide me through the process, you asked me to just do a pull request and we'll take it from there, which I did.
Are you available tomorrow for a call at 10?

/Szabolcs

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by nagyszblcs2** [comment]
I made it according to the examples and documentation available. Saying poor is not in any way constructive in helping to solve this issue. I will ask you to reply to me emails and have a call about it.

**Comment by jmcanterafonseca** [comment]
there are still indentation issues with JSON but we will fix it later

**Pull request merged**
